# Approved an existing repot
POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "bmw",
    "model": "m6",
    "price": 150.00,
    "year": 1990,
    "mileage": 1000,
    "lng": 153,
    "lat": 45
}


# ## Approved an existing repot
# PATCH  http://localhost:3000/reports/6
# Content-Type: application/json
# {
#     "approved": true
# }
